### ISSUE TITLE
如何在生产环境部署呢？请教一下

### ISSUE THREAD

**Issue by crossskyLi** [MinJieLiu/micro-app#2]
我这边试过开发环境都是OK的。但是我在思考如何部署到生产环境的时候，我不知该如何配置。请指教一下，多谢

**Comment by crossskyLi** [comment]
我在preview模式下，添加以下代码，并且我把vue和react子应用的构建产物放到react 主应用的 dist目录下，preview 是可以正常显示的。但这个应该不是便捷操作，请问怎样才是符合的。
![image](https://user-images.githubusercontent.com/24408773/157157962-30fdd11b-edc6-4211-a1a8-4be63c9550fc.png)

**Comment by MinJieLiu** [comment]
这种部署方式应当再封装一层，针对 dev 模式做单独调试。部署走工作流的方式

**Comment by MinJieLiu** [comment]
每个项目的部署方式不尽相同，可以沉淀自己的部署方式，通过自动化部署解决此类问题

**Comment by MinJieLiu** [comment]
关于调试方面的判断问题，可以所有的 entry 指向生产环境。本地调试通过代理 entry 重定向 本地代码

**Comment by crossskyLi** [comment]
发了邮件在你的个人邮箱。是否可以加下你的微信。沟通有无。

**Comment by crossskyLi** [comment]
我明白你的思路了。多谢。
