### ISSUE TITLE
关于styleInject这个方法，为什么用的是prepend而不是appendChild呢？

### ISSUE THREAD

**Issue by JayeeHsu** [MinJieLiu/micro-app#7]
```
defineApp.styleInject = (parentNode) => {
  ${cssChunksStr}.forEach((css) => {
    const link = createLink(new URL(css, import.meta['url']));
    parentNode.prepend(link);
  });
};
```
我看源码里这块地方用的是prepend

我提出这个问题的原因是我目前的微前端项目中vite分包后产出的css顺序没办法控制（我的cssSplitCode是默认的true），build后产出的css列表按照appendChidl顺序插入后，会产生与dev模式不同的表现，比如有两个相同优先级的class A和B，在dev模式下，A在B后，样式表现的是A，在build后拆包产出的顺序B在A后，用appendChild导致B在A后加载，样式表现的就为B了

**Comment by MinJieLiu** [comment]
原本出现了与 react-dom 渲染冲突。现在发现没什么问题，已修复。使用此方式必须得注意，antd Notification 此类的组件在路由跳转后会停留一段时间。如果样式被移除掉了可能会无法关闭。
因此 
```
+ @micro-web/vite-plugin 0.3.0
```
新增了 styleAppendTo  可设置为 `document.head`
