### ISSUE TITLE
可以进行更细粒度的复用吗？

### ISSUE THREAD

**Issue by He110te4m** [MinJieLiu/micro-app#9]
比如说只需要复用其中的某些页面或者某些组件？

**Comment by MinJieLiu** [comment]
可以的，颗粒度自己定

**Comment by He110te4m** [comment]
> 可以的，颗粒度自己定

有 Demo 吗？看 vite 代码写死了 main.ts 入口，如果只是 expose 项目的某个组件（有其他关联的组件），需要怎么改呢？把所有关联的代码单独抽一个项目出来吗？

**Comment by MinJieLiu** [comment]
rollup 不是可以 output 单独打包出很多的组件吗，单独加载就可以了

**Comment by He110te4m** [comment]
感觉说的不是一个事，vite 插件里面写死了 [chunk 的处理方式](https://github.com/MinJieLiu/micro-app/blob/main/packages/micro-vite-plugin/index.ts#L51)，后面的单独配置 input，没法按着这样分包构建。。

放弃了，用别的工具了。

**Comment by xhblovewmy** [comment]
> 

我也遇到了类似的需求，请问你找到了合适的工具或者解决方案了吗？

**Comment by He110te4m** [comment]
> > 
> 
> 我也遇到了类似的需求，请问你找到了合适的工具或者解决方案了吗？

vite 的社区提供了一个插件， [vite-plugin-federation](https://github.com/originjs/vite-plugin-federation) ，但是不支持 vite4，目前看好像也没有什么修复的意思，bug 有点多，最后我选了 [module-federation/vite](https://github.com/module-federation/vite) ，底层工具是模块联邦联盟的人做的（成员里也有 webpack 模块联邦的 creator），跟构建工具无关，而且有统一标准，目前来看我的场景这里面都能覆盖全
